# Generated by Django 4.0.3 on 2022-07-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('permissao', models.IntegerField(db_column='Permissao')),
            ],
            options={
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('funcao', models.CharField(blank=True, db_column='Funcao', max_length=255, null=True)),
                ('permissao', models.IntegerField(db_column='Permissao')),
            ],
            options={
                'db_table': 'Funcionario',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero_do_lugar', models.IntegerField(blank=True, db_column='Numero do lugar', null=True)),
                ('estado', models.CharField(db_column='Estado', default='Disponivel', max_length=255)),
            ],
            options={
                'db_table': 'Lugar',
            },
        ),
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True, unique=True)),
                ('capacidade', models.IntegerField(db_column='Capacidade')),
                ('zonas', models.IntegerField(db_column='Zonas')),
                ('estado', models.CharField(db_column='Estado', default='Aberto', max_length=50)),
                ('morada', models.CharField(blank=True, db_column='Morada', max_length=255, null=True, unique=True)),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=60, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('foto', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'Parque',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero_da_zona', models.IntegerField(blank=True, db_column='Numero da zona', null=True, unique=True)),
                ('lugares', models.IntegerField(db_column='Lugares')),
                ('tipo_de_zona', models.CharField(blank=True, db_column='Tipo de zona', max_length=255, null=True)),
                ('parqueid', models.ForeignKey(db_column='ParqueID', on_delete=django.db.models.deletion.CASCADE, to='AdminManagement.parque')),
            ],
            options={
                'db_table': 'Zona',
            },
        ),
    ]
