# Generated by Django 4.0.2 on 2022-07-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManagement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='numero_do_lugar',
            field=models.IntegerField(blank=True, db_column='Numero do lugar', null=True, unique=True),
        ),
    ]
